### ISSUE TITLE
-> self.D_mtrain = len(self.D.MTRAIN)

### ISSUE THREAD

**Issue by Yanxing-Shi** [FerranAlet/modular-metalearning#2]
I have theses mistakes:
```
> /home/user/code/modular-metalearning/modular_metalearning.py(223)create_dataset()
-> self.D_mtrain = len(self.D.MTRAIN)
(Pdb) 
(Pdb) 
```

**Comment by FerranAlet** [comment]
Sorry for the very late response. This isn't a mistake, it's just pdb.set_trace() on the line before to give the possibility of inspecting some variables, if the user wants. Since it can cause confusion I've removed it.
