### ISSUE TITLE
neurips2019: link for the data is invalid

### ISSUE THREAD

**Issue by hilbert9221** [FerranAlet/modular-metalearning#5]
In ./neurips/REAME.md, the link (https://lis.csail.mit.edu/alet/neurips2019_data/) for the data seems invalid. Would you mind checking the validity of the link? I hope to better understand the code by running it.

**Comment by FerranAlet** [comment]
Oops, my lab changed the website back-end and that broke the link. Should be solved now, thanks for noticing @hilbert9221!

**Comment by hilbert9221** [comment]
I have successfully downloaded the data and run the code. Thank you so much.
